#!/usr/bin/env bash

#
# Install ssh.
#
# Author: Tyll Weiß <inkdpixels@gmail.com>
#
DOT_DIR="$HOME/.dotfiles"

source $DOT_DIR/lib/utils/typography
source $DOT_DIR/lib/utils/typeExists

#
# Install npm if not already installed.
#
if typeExists "ssh"; then
	p_success "ssh is already installed. Continuing..."
else
	p_info "Installing ssh..."

	if type_exists "brew"; then
		brew tap homebrew/dupes
		brew install openssh

		if ! type_exists "ssh"; then
			p_fail "Command 'ssh' is still NOT in your path, you may need to restart your shell session and re-run this command."

			exit 1
		fi
	else
		p_warn "Currently we only install OpenSSH if homebrew is installed on your system. You may want to install OpenSSH yourself since homebrew couldn't be found."
	fi
fi
