#!/usr/bin/env bash

#
# Install git and the global configuration files.
#
# Author: Tyll Weiß <inkdpixels@gmail.com>
#
DOT_DIR="$HOME/.dotfiles"

source $DOT_DIR/lib/utils/install
source $DOT_DIR/lib/utils/symlink
source $DOT_DIR/lib/constants/os
source $DOT_DIR/lib/utils/typography

#
# Install the binary if not already installed.
#
install "git"

#
# Symlink/create the global configuration.
#
p_info "Symlinking the global .gitconfig..."
symlink "$DOT_DIR/git/.gitconfig" "$HOME/.gitconfig"

if [ "$OS" == "OSX" ]; then
	p_warn "On OSX we also recommend setting 'git config --global credential.helper osxkeychain'."
	echo ""
fi

p_info "Symlinking the global .gitignore..."
symlink "$DOT_DIR/git/.gitignore" "$HOME/.gitignore"
