#!/usr/bin/env bash

#
# Downloads the eg sources and symlinks the binary to the path.
#
# Author: Tyll Weiß <inkdpixels@gmail.com>
#
DOT_DIR="$HOME/.dotfiles"

source $DOT_DIR/lib/utils/symlink
source $DOT_DIR/lib/utils/typography
source $DOT_DIR/lib/utils/fileExists

#
# Symlink/create the global configuration.
#
if [ ! -d "$DOT_DIR/eg/src" ]; then
	p_info "Installing the 'eg' command..."
	git clone https://github.com/srsudar/eg $DOT_DIR/eg/src
	symlink "$DOT_DIR/eg/src/eg_exec.py" "/usr/local/bin/eg"
else
	p_success "Command 'eg' already installed. Continuing..."
fi
