#!/usr/bin/env bash

#
# Update homebrew and cleanup all outdated recipes.
#
# Author: Tyll Weiß <inkdpixels@gmail.com>
#
DOT_DIR="$HOME/.dotfiles"

source $DOT_DIR/utils/typeExists
source $DOT_DIR/utils/typography

if typeExists "brew"; then
	p_info "Updating homebrew..."
	brew update

	p_info "Upgrading all installed homebrew formulas..."
	brew upgrade

	p_info "Removing the outdated homebrew formulas..."
	brew cleanup
fi
