#!/bin/bash

BASE_DIR="$HOME/.dotfiles"

#
# A helper function which returns to the base directory.
# Should be ran after executing your test statements.
#
afterEach() {
	# Change back into the root directory.
	cd ".."

	rm -rf test_working_dir

	# Delete all output result diffs.
	OUTPUT_RESULTS=$BASE_DIR/tests/output/*.result.txt
	for result in $OUTPUT_RESULTS
	do
		if [ -f "$result" ]; then
			rm $result
		fi
	done
}
