#!/bin/bash

#
# A helper function which cleans up the testing working directory.
#
beforeEach() {
	#
	# Create placeholders for the CLI output tests.
	#
	touch "tests/output/help.result.txt"

	mkdir test_working_dir && cd test_working_dir
}
