#!/bin/bash

# A Brew-Cask function to check if an application already is installed
# Function is from https://github.com/mathiasbynens/dotfiles/blob/master/.brew
function installcask() {
	if brew cask info "${@}" | grep "Not installed" > /dev/null; then
		brew cask install "${@}"
	else
		echo "${@} is already installed."
	fi
}

# Install all basic applications to setup a production system
installcask blender
installcask dropbox
installcask firefox
installcask firefox-aurora
installcask google-chrome
installcask google-chrome-canary
installcask gmail-notifr
installcask growlnotify
installcask insync
installcask imagealpha
installcask imageoptim
installcask iterm2
installcask keepass-x
installcask libre-office
installcask opera
installcask phpstorm
installcask skype
installcask spotify
installcask sublime-text
installcask the-unarchiver
installcask thunderbird
installcask twitter
installcask virtualbox
installcask vlc
installcask webstorm