#!/bin/bash

install_deps() {
    # Check for the CLT
    if ! type_exists 'gcc'; then
        e_error "The XCode Command Line Tools must be installed first."
        echo "  https://developer.apple.com/downloads"
        exit 1
    else
        e_success "The XCode Command Line Tools are installed."
    fi

    # Check for Homebrew
    if ! type_exists 'brew'; then
        e_header "Installing Homebrew..."
        ruby -e "$(curl -fsSkL raw.github.com/mxcl/homebrew/go)"
        if ! type_exists 'brew'; then
            e_success "Homebrew is installed."
        else
            e_error "Something went wrong."
            exit 1
        fi
    else
        e_success "Homebrew is installed."
    fi

    # Make sure we’re using the latest Homebrew
    brew update

    # Upgrade any already-installed formulae
    brew upgrade

    # Check for git
    if ! type_exists 'git'; then
        e_header "Updating Homebrew..."
        brew update
        e_header "Installing Git..."
        brew install git
        if ! type_exists 'git'; then
            e_success "Git is installed."
        else
            e_error "Something went wrong."
            exit 1
        fi
    else
        e_success "git is installed."
    fi

    # Check for 'z'
    if [ -d "~/code/z/z.sh" ] ; then
        e_header "  Fetching the latest version of 'z'..."
        mkdir -p ~/code/z
        curl https://raw.github.com/rupa/z/master/z.sh > ~/code/z/z.sh
        chmod +x ~/code/z/z.sh
    else
        e_success "'z' is installed."
    fi
    echo
}