#!/bin/bash

# Header logging
e_header() {
	echo "\n$(tput bold ; tput setaf 6)$@$(tput sgr0)";
}

# Success logging
e_success() {
	echo "$(tput setaf 64)✓ $@$(tput sgr0)";
}

# Error logging
e_error() {
	echo "$(tput setaf 1)x $@$(tput sgr0)";
}

# Warning logging
e_warning() {
	echo "$(tput setaf 136)! $@$(tput sgr0)";
}

# Move on message
e_moveon() {
	echo "$(tput setaf 6)⇓ $@$(tput sgr0)";
}



# Test whether a command exists
# $1 - cmd to test
type_exists() {
	if [ `type -P $1` ]; then
	  return 0
	fi
	return 1
}

# Simlink helper
link() {
	# Force create/replace the symlink.
	ln -fs "${DOTFILES}/${1}" "${HOME}/${2}"
}