#!/usr/bin/env bash

#
# Symlinks the atom configuration files.
#
# Author: Tyll Weiß <inkdpixels@gmail.com>
#
DOT_DIR="$HOME/.dotfiles"

source $DOT_DIR/lib/utils/symlink
source $DOT_DIR/lib/utils/typography
source $DOT_DIR/lib/utils/fileExists

#
# Symlink/create the global configuration.
#
if [ -d "$HOME/.atom" ]; then
	p_info "Installing the global atom configuration..."
	mkdir -p "$HOME/.atom"
	symlink "$DOT_DIR/atom/config.cson" "$HOME/.atom/config.cson"
	symlink "$DOT_DIR/atom/snippets.cson" "$HOME/.atom/snippets.cson"
fi
