#!/usr/bin/env bash

# System overrides
alias ls="gls -lAh --color" # Use the grc 'ls' command iwith colored outpu instead of the native one

# Easier 'cd' navigation: .., ... etc.
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

# Git Aliases
alias gps='git push'
alias gpl='git pull'
alias gc='git commit -m'
alias gd='git diff'
alias gco='git checkout'
alias gb='git branch'
alias gs='git status -sb'