#!/usr/bin/env bash

#
# Installs all dependencies and optional tools.
#
# Author: Tyll Weiß <inkdpixels@gmail.com>
#
DOT_DIR="$HOME/.dotfiles"

for file in $DOT_DIR/{git,bash,nvm,composer,npm,atom,z}/install; do
	[ -r "$file" ] && [ -f "$file" ] && . "$file";
done;
unset file;
