#!/usr/bin/env bash

#
# Install nvm and set the correct nvm stable version.
#
# Author: Tyll Weiß <inkdpixels@gmail.com>
#
DOT_DIR="$HOME/.dotfiles"

source $DOT_DIR/lib/utils/typography
source $DOT_DIR/lib/utils/typeExists

if typeExists "npm"; then
	p_success "npm is installed. Continuing..."
else
	p_info "Installing npm..."
	curl https://www.npmjs.org/install.sh | sh

	if ! type_exists "npm"; then
		p_fail "Command 'npm' is still NOT in your path, you may need to restart your shell session to continue."

		exit 1
	fi
fi

p_info "Symlinking the global .npmrc..."
symlink "$DOT_DIR/npm/.npmrc" "$HOME/.npmrc"
